### ISSUE TITLE
Crash if showing lateral menu

### ISSUE THREAD

**Issue by stemy2** [mueller-ma/TabletopTools#107]
**Describe the bug**
I can't see lateral menu, clicking on the hamburger menu makes the app crash'

**To Reproduce**
1. Click on hamburger menu

**Expected behavior**
The menu appears.

**Device (please complete the following information):**
 - Device: Samsung Galaxy S7
 - Android version: 8.1

**Comment by mueller-ma** [comment]
Can you capture the adb log?
