### ISSUE TITLE
Black theme for amoled screens

### ISSUE THREAD

**Issue by Hunter16g** [mueller-ma/TabletopTools#141]
This app follows system theme which is nice, however a black theme would be good to have.

**Comment by mueller-ma** [comment]
Thanks for your suggestion, but I'd like to keep the theming simple; that is: always follow system.

**Comment by Hunter16g** [comment]
> Thanks for your suggestion, but I'd like to keep the theming simple; that is: always follow system.

Ok, I understand. Just note however that it does not follow system in this case (I mean Tabletop tools will keep using normal dark theme when pure black dark theme is enabled in the system settings).

**Comment by Hunter16g** [comment]
I'm on LineageOS 18.1 and no, the other apps don't use pure black when I set "follow system".

**Comment by mueller-ma** [comment]
I see. This is a LineageOS-only API and therefore I cannot implement support.
