### ISSUE TITLE
"Add to count" slider missing from dice screen

### ISSUE THREAD

**Issue by jplandolt** [mueller-ma/TabletopTools#170]
**Describe the bug**
The "Add to count" slider, right below the "Number of dice" slider, is not showing up on the dice screen even though the code appears active in the project layout screen.

**To Reproduce**
1. Open Project in Android Studio
2. Click on 'Layout',then 'content_main'
3. Observe both slider bars
4. Build App, run in Emulator
5. Observe only the single slider, "Number of dice: x"

**Expected behavior**

**Screenshots**
1. Layout Editor in Android Studio:
![Screenshot 2022-10-12 203651](https://user-images.githubusercontent.com/951943/195472827-6d99ab0a-e5a0-4501-990a-a32e791b1e41.png)

2. Sreen from App (running in emulator)
![Screenshot 2022-10-12 204054](https://user-images.githubusercontent.com/951943/195472973-b9b31c9f-f013-49e1-8ecf-e6945e7e28f5.png)

**Device :**
 - Pixel 5 (API 33)
 - Android 13

**Comment by mueller-ma** [comment]
Did you enable the string in the settings?

**Comment by jplandolt** [comment]
I did not see the settings switch before. Thank you!
