### ISSUE TITLE
leave the "About" page > app crashes

### ISSUE THREAD

**Issue by EVOTk** [mueller-ma/TabletopTools#175]
**Describe the bug**
The app crashes if I want to leave the "About" page

**To Reproduce**
1. Go to Parameters
2. Click on About
3. Click on Other section in Menu
4. App crashes

**Expected behavior**
No Crash :)

**Screenshots**
https://user-images.githubusercontent.com/45015615/197058287-b1965609-1d78-4438-89df-f6a08a10bfaf.mp4

**Device (please complete the following information):**
 - Device: Honor 70
 - Android version: 12
 - Tabletop Tools : 1.15

**Comment by bladebunny** [comment]
I was able to verify this bug and have submitted a PR for it.

**Comment by EVOTk** [comment]
It works very well thank you
