### ISSUE TITLE
Sound for buzzer

### ISSUE THREAD

**Issue by vertigo220** [mueller-ma/TabletopTools#192]
**Is your feature request related to a problem? Please describe.**
I'm assuming this isn't a bug where there's supposed to be sound and I'm just not getting any, though it does seem odd that a "buzzer" would be made that doesn't buzz, but that's what's happening for me. All it does is vibrate.

**Describe the solution you'd like**
Make the buzzer play a buzzing sound, preferably with a variety of sounds that can be selected.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mueller-ma** [comment]
If you find a suitable sound file, that can be used on free software, I can include it.

**Comment by mueller-ma** [comment]
If you could trim and upload them here it would be great.

> Buzzer (# 2), Buzzer 49456 (# 3), Basketball buzzer (# 5), Bell ring buzzer (# 6), Electric fence fx (# 11), Ice hockey sports buzzer (# 15), and Wrong long buzzer (# 25)

👍 All of them should be fine to include.

**Comment by vertigo220** [comment]
What file format is best? WAV, MP3, Ogg, etc.

**Comment by mueller-ma** [comment]
Currently the app includes one mp3 file and there are no issue with that: https://github.com/mueller-ma/TabletopTools/blob/main/app/src/main/res/raw/beeps.mp3

So let's go for mp3 again.

**Comment by mueller-ma** [comment]
@vertigo220 I included the "Apartment buzzer bell press", but feel free to post other sounds here, so I can include them.
