### ISSUE TITLE
Allow multiple tools to be used simultaneously

### ISSUE THREAD

**Issue by vertigo220** [mueller-ma/TabletopTools#193]
**Is your feature request related to a problem? Please describe.**
Games often require more than one of these tools at the same time. For example, I downloaded this to use for Taboo (ended up not using due to the buzzer not buzzing), and in that game you need to be able to run a timer and, with that running, use the buzzer. This is currently possible by switching back and forth, but that's very cumbersome.

**Describe the solution you'd like**
Add ability to use multiple tools together. One possibility would be to run them in a sort of split-screen, another slightly less useful option, though still better than the current setup, would be to open them in tabs that can be quickly switched by either tapping the tab or swiping side to side. As mentioned, the timer and buzzer should be able to be used together, and probably the timer and dice as well. I can't think of when dice and buzzer or all three would need to be used together, but the ability should probably be there just in case if not too difficult.

**Describe alternatives you've considered**
Another possibility would be to allow the timer time to be set and the timer to be enabled, then have it show in the corner on the other screens (or at least the dice and buzzer screens) so it can be tapped to start/pause/reset it from those screens.

**Additional context**
N/A

**Comment by eightys3v3n** [comment]
If using the tabs or swipe-between option here, it would be awesome to be able to reorder the options.
So if I need to use thetimer and dice, I can put them next to each other so swiping left once gets the timer, then swiping right once gets back to dice.

**Comment by vertigo220** [comment]
Only thing is need to be careful with swiping that the timer isn't accidentally tapped and paused when doing so. Another reason to show it on all screens, at least if it's running.

**Comment by quasart** [comment]
I think the tools are a bit too complex to see multiple of them on the same screen, but I've made a web app with simpler tools allowing that:

https://quasart.frama.io/tatoge/

**Comment by mueller-ma** [comment]
The multi-window feature of Android could be used to achieve this feature. Then only small changes are required for the app.
