### ISSUE TITLE
Update dependencies 

### ISSUE THREAD

**Issue by mueller-ma** [mueller-ma/TabletopTools#255]
1. Pick one dependency from https://github.com/mueller-ma/TabletopTools/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies
2. Fix all build issues and warnings.
3. Push fixes and bumped version to a new branch.
4. Open a pull request.

**Comment by krishnachaitanya0107** [comment]
Hi @mueller-ma ,

I would like to work on this issue , could you please assign it to me .

Thanks

**Comment by mueller-ma** [comment]
Just pick one PR, no need to assign you here :)
