### ISSUE TITLE
Make timer configurable

### ISSUE THREAD

**Issue by mueller-ma** [mueller-ma/TabletopTools#57]
Currently the timer is always set to 5 minutes, which is useful for some cases. However it would be more useful if the timer is configurable.

**Comment by Kardelio** [comment]
Hey there @mueller-ma would it be ok If i had a good of this ticket? 

I have already had a look at the code and can see the `DEFAULT_TIMER` value being used in the `FMTFragment` so if I understand correctly, I should instead enable the user to input the time that they wish for the timer and use that value instead?

**Comment by mueller-ma** [comment]
Yes, that's correct. IMO the selected value should be saved to SharedPreferences as well and be the default

**Comment by Kardelio** [comment]
Sounds good to me, mind if I take a crack at it then? @mueller-ma

**Comment by mueller-ma** [comment]
Sure, you can give it a try.

**Comment by Kardelio** [comment]
Thanks @mueller-ma ill get on it 👍

**Comment by Kardelio** [comment]
Addressed by #61 

Let me know what you think 👍  @mueller-ma

**Comment by Kardelio** [comment]
@mueller-ma cheers matey!
Also thanks for letting me get involved this was an ace project and I really ike your style and approach!
Let me know if there is anything else I can help with?

**Comment by mueller-ma** [comment]
Sure,  you can have a look at the open issues here.
