### ISSUE TITLE
Action bar item to keep screen on

### ISSUE THREAD

**Issue by mueller-ma** [mueller-ma/TabletopTools#58]
Currently the screen is kept on on the timer page. An item in the action bar would be useful that toggles "keep screen on".

On the timer page this setting should be locked and always turned on.

**Comment by theAkito** [comment]
I would like to tackle this issue.

**Comment by mueller-ma** [comment]
Some fragments, e.g. timer, keep already the screen on, so the action bar item should be disabled/hidden for these fragments.

**Comment by theAkito** [comment]
Ah, now I get it. I was a bit confused from your first description. I thought you wanted a toggle specifically for the timer page. 😄
