### ISSUE TITLE
Timer: Play sound included in the app

### ISSUE THREAD

**Issue by mueller-ma** [mueller-ma/TabletopTools#64]
Currently the timer plays the default ring tone when it expires. I'm not sure what happens when the phone is muted or the default ring tone isn't set.
The app should include a free (no cost and under free license) ring tone that is played when the timer expires and the phone should vibrate shortly.

**Comment by Kardelio** [comment]
Hey!
How is this project all still going?
I would love to help here again if I can?

Is this ticket still eligible for picking up? If so I would love to grab it?

**Comment by mueller-ma** [comment]
Sure, you can give it a try and open a (draft) PR.

**Comment by Kardelio** [comment]
OKie dokie :) ty

**Comment by Kardelio** [comment]
hey @mueller-ma do you have a specific audio file in mind to play when the timer finishes? Or should I just pick a nice free / license ok audio file to include?

**Comment by Kardelio** [comment]
Maybe something from this site: https://soundbible.com/royalty-free-sounds-1.html

@mueller-ma ?

**Comment by mueller-ma** [comment]
You can use a suitable royalty free sound from this side.

**Comment by mueller-ma** [comment]
Maybe one of these:

- https://soundbible.com/529-Pager-Beeps.html
- https://soundbible.com/2061-Loud-Alarm-Clock-Buzzer.html

**Comment by Kardelio** [comment]
@mueller-ma oooo yeh love that first one! Ill go for that one if thats all good with you!

**Comment by mueller-ma** [comment]
Fixed by #85
