### ISSUE TITLE
Dice Count Increment

### ISSUE THREAD

**Issue by jplandolt** [mueller-ma/TabletopTools#80]
I'd like to have a modifier to the rolled dice total, eg, 3d6 "+5"

**Describe the solution you'd like**
Add a slider below the dice count to select a value (0-10) to increment the final dice total

**Additional context**
common for RPG roles to have a modifier on the roll

**Comment by jplandolt** [comment]
I've written the code (an easy extension based upon existing code around the dicer slider) for your consideration; As I am a very infrequent contributor to projects, please let me know how best I can support your project.  Can you create a feature branch for my work?

**Comment by mueller-ma** [comment]
You can fork this repository, push your changes there and open a PR.

**Comment by jplandolt** [comment]
PR Created - Dice Count Increment #81

**Comment by jplandolt** [comment]
I am VERY much a rookie at ui layout, so it is likely that adjustments will be needed regarding the placement of the increment slider
